### ISSUE TITLE
Cannot declare class TuyaCloud, because the name is already in use

### ISSUE THREAD

**Issue by chaaawles** [Aymkdn/tuyacloud-php#3] opened 2020-06-29 08:40 UTC
added require_once('TuyaCloud.php') in the code but still gives this error.
![image](https://user-images.githubusercontent.com/52267922/85992093-fd55be80-ba26-11ea-8536-37bec2926b5a.png)

**Comment by Aymkdn** [comment] 2020-06-29 08:46
I don't think it's related to my lib. Make sure you don't call TuyaCloud.php several times, or that you don't have a function called TuyaCloud, or a variable, or anything with that name in your code.

I've just tried to use `__contruct` and it works perfectly for me.

I will close this issue because the issue is not related to my lib (except if you can prove the contrary).

**Closed as completed by Aymkdn** 2020-06-29 08:46 UTC
